// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import {Fira_Code,Ubuntu_Mono,Source_Code_Pro} from "next/font/google";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

const firaCode = Fira_Code({
  variable: "--font-fira-code",
  subsets: ["latin"],
  display: "swap",
});
const ubuntuMono = Ubuntu_Mono({
  variable: "--font-ubuntu-mono",
  subsets: ["latin"],
  weight:['400','700'],
  display: "swap",
});
const sourceCodePro = Source_Code_Pro({
  variable: "--font-source-code-pro",
  subsets: ["latin"],
  display: "swap",
});


export const metadata = {
  title: "mAuld",
  description: "Generated by mmaulidinabdi",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en"  className={`${firaCode.variable} ${sourceCodePro.variable} ${ubuntuMono.variable}`}>
      <body
        className={`antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
